//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlExplorer.C1Gallery {
    
    
    public partial class Iframe {
        
        /// <summary>
        /// gallery control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Gallery.C1Gallery gallery;
    }
}
