//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlExplorer.C1Pager {
    
    
    public partial class Modes {
        
        /// <summary>
        /// C1PagerNextPrevious control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Pager.C1Pager C1PagerNextPrevious;
        
        /// <summary>
        /// C1PagerNextPrevious2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Pager.C1Pager C1PagerNextPrevious2;
        
        /// <summary>
        /// C1PagerNextPrevious3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Pager.C1Pager C1PagerNextPrevious3;
        
        /// <summary>
        /// C1PagerNextPreviousFirstLast control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Pager.C1Pager C1PagerNextPreviousFirstLast;
        
        /// <summary>
        /// C1PagerrNextPreviousFirstLast2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Pager.C1Pager C1PagerrNextPreviousFirstLast2;
        
        /// <summary>
        /// C1PagerNextPreviousFirstLast3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Pager.C1Pager C1PagerNextPreviousFirstLast3;
        
        /// <summary>
        /// C1PagerNumeric control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Pager.C1Pager C1PagerNumeric;
        
        /// <summary>
        /// C1PagerNumericFirstLast control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Pager.C1Pager C1PagerNumericFirstLast;
        
        /// <summary>
        /// C1PagerNumericFirstLast2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Pager.C1Pager C1PagerNumericFirstLast2;
        
        /// <summary>
        /// C1PagerNumericFirstLast3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Pager.C1Pager C1PagerNumericFirstLast3;
    }
}
