//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlExplorer.C1Wizard {
    
    
    public partial class Pager {
        
        /// <summary>
        /// C1Wizard1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Wizard.C1Wizard C1Wizard1;
        
        /// <summary>
        /// C1WizardStep1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Wizard.C1WizardStep C1WizardStep1;
        
        /// <summary>
        /// C1WizardStep2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Wizard.C1WizardStep C1WizardStep2;
        
        /// <summary>
        /// C1WizardStep3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Wizard.C1WizardStep C1WizardStep3;
        
        /// <summary>
        /// C1WizardStep4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Wizard.C1WizardStep C1WizardStep4;
        
        /// <summary>
        /// C1WizardStep5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Wizard.C1WizardStep C1WizardStep5;
        
        /// <summary>
        /// C1WizardStep6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Wizard.C1WizardStep C1WizardStep6;
        
        /// <summary>
        /// C1WizardStep7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Wizard.C1WizardStep C1WizardStep7;
        
        /// <summary>
        /// C1Pager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Pager.C1Pager C1Pager1;
    }
}
