//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlExplorer.C1Carousel {
    
    
    public partial class Paging {
        
        /// <summary>
        /// C1Carousel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1Carousel C1Carousel1;
        
        /// <summary>
        /// C1CarouselItem1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem1;
        
        /// <summary>
        /// C1CarouselItem2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem2;
        
        /// <summary>
        /// C1CarouselItem3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem3;
        
        /// <summary>
        /// C1CarouselItem4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem4;
        
        /// <summary>
        /// C1CarouselItem5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem5;
        
        /// <summary>
        /// C1Carousel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1Carousel C1Carousel2;
        
        /// <summary>
        /// C1CarouselItem7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem7;
        
        /// <summary>
        /// C1CarouselItem8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem8;
        
        /// <summary>
        /// C1CarouselItem9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem9;
        
        /// <summary>
        /// C1CarouselItem10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem10;
        
        /// <summary>
        /// C1CarouselItem11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem11;
        
        /// <summary>
        /// C1Carousel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1Carousel C1Carousel3;
        
        /// <summary>
        /// C1CarouselItem13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem13;
        
        /// <summary>
        /// C1CarouselItem14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem14;
        
        /// <summary>
        /// C1CarouselItem15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem15;
        
        /// <summary>
        /// C1CarouselItem16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem16;
        
        /// <summary>
        /// C1CarouselItem17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.Wijmo.Controls.C1Carousel.C1CarouselItem C1CarouselItem17;
    }
}
