//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class C1LineChart_Trendline {
    
    /// <summary>
    /// C1LineChart1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::C1.Web.Wijmo.Controls.C1Chart.C1LineChart C1LineChart1;
    
    /// <summary>
    /// inputOrder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::C1.Web.Wijmo.Controls.C1Input.C1InputNumeric inputOrder;
    
    /// <summary>
    /// inputSampleCount control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::C1.Web.Wijmo.Controls.C1Input.C1InputNumeric inputSampleCount;
    
    /// <summary>
    /// dplFitType control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.DropDownList dplFitType;
    
    /// <summary>
    /// btnApply control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnApply;
}
