//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlExplorer {
    
    
    public partial class GetSourceCode {
        
        /// <summary>
        /// LblASPX control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Wilco.Web.SyntaxHighlighting.SyntaxHighlighter LblASPX;
        
        /// <summary>
        /// LblCS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Wilco.Web.SyntaxHighlighting.SyntaxHighlighter LblCS;
    }
}
